#!/usr/bin/env zsh

NAMESPACE="$1"
ACTION="$2"
SELECTED_LINE="$3"

act() {
	local container="$1"
	if [[ "$ACTION" == "tail" ]]; then
		kubectl --namespace="$NAMESPACE" logs -f "$NAME" -c "$container"
	elif [[ "$ACTION" == "fzf" ]]; then
		kubectl --namespace="$NAMESPACE" logs "$NAME" -c "$container" | fzf --height='100%'
	elif [[ "$ACTION" == "bat" ]]; then
		kubectl --namespace="$NAMESPACE" logs "$NAME" -c "$container" | bat --paging=always
    fi
}

if [[ "$NAMESPACE" == "all" ]]; then
	NAMESPACE=$(echo "$SELECTED_LINE" | awk '{ print $1 }')
	NAME=$(echo "$SELECTED_LINE" | awk '{ print $2 }')
else 
	NAME=$(echo "$SELECTED_LINE" | awk '{ print $1 }')
fi

CONTAINERS=($(kubectl --namespace=$NAMESPACE get pod $NAME --output=jsonpath='{.spec.containers[*].name}'))

if [[ ${#CONTAINERS[*]} == 1 ]]; then
	act "${CONTAINERS[1]}"
else
	SELECTED=$(echo ${CONTAINERS[*]} | tr ' ' '\n' | fzf --header='Select a container:')
	act "$SELECTED"
fi

