#!/usr/bin/env zsh

NAMESPACE="$1"
WORKLOAD="$2"
SELECTED_LINE="$3"

if [[ "$NAMESPACE" == "all" ]]; then
	NAMESPACE=$(echo "$SELECTED_LINE" | awk '{ print $1 }')
	NAME=$(echo "$SELECTED_LINE" | awk '{ print $2 }')
else 
	NAME=$(echo "$SELECTED_LINE" | awk '{ print $1 }')
fi

kubectl --namespace="$NAMESPACE" get "$WORKLOAD" "$NAME" -o yaml | bat --paging=always --language=yaml