#!/usr/bin/env zsh

COMMAND="$@"
osascript -e \
	'tell application "Terminal" to activate'
osascript -e \
	'tell application "System Events" to tell process "Terminal" to keystroke "t" using command down'
osascript -e \
	"tell application \"Terminal\" to do script \"$COMMAND[*]\" in selected tab of the front window"