# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source "$HOME/.zplug/init.zsh"

OHMY_ZSH_HASH="1e11a3c"
zplug "plugins/gitfast", from:oh-my-zsh, as:plugin, at:"$OHMY_ZSH_HASH"
zplug "plugins/osx", from:oh-my-zsh, as:plugin, at:"$OHMY_ZSH_HASH"
zplug "robbyrussell/oh-my-zsh", use:"lib/*.zsh", at:"$OHMY_ZSH_HASH"

zplug "zsh-users/zsh-autosuggestions", as:plugin, at:"v0.5.0", defer:2
zplug "zsh-users/zsh-syntax-highlighting", as:plugin, at:"a109ab5", defer:2

# Powerlevel10k configuration is in p10k.zsh
zplug romkatv/powerlevel10k, as:theme, depth:1, at:"v1.14.3"

zplug "wfxr/forgit", as:plugin, defer:1
zplug "wfxr/formarks", as:plugin, defer:1

# Setup scripts and plugins from the local filesystem
DOTFILES_ZSH="$HOME/dotfiles/zsh"
zplug "$DOTFILES_ZSH", from:local, use:"**/*.zsh", defer:3
zplug "$DOTFILES_ZSH/fzf-kubectl", from:local, use:"__fzf-kubectl*", as:command

zplug "$HOME", from:local, use:".secret-envs.sh"

zplug load

