source "$HOME/.zplug/init.zsh"

OHMY_ZSH_HASH="1e11a3c"
zplug "plugins/gitfast", from:oh-my-zsh, as:plugin, at:"$OHMY_ZSH_HASH"
zplug "plugins/osx", from:oh-my-zsh, as:plugin, at:"$OHMY_ZSH_HASH"
zplug "robbyrussell/oh-my-zsh", use:"lib/*.zsh", at:"$OHMY_ZSH_HASH"

zplug "zsh-users/zsh-autosuggestions", as:plugin, at:"v0.5.0", defer:2
zplug "zsh-users/zsh-syntax-highlighting", as:plugin, at:"a109ab5", defer:2

zplug "bhilburn/powerlevel9k", as:theme, at:"v0.6.7"

zplug "wfxr/forgit", as:plugin, defer:1
zplug "wfxr/formarks", as:plugin, defer:1

# Setup scripts and plugins from the local filesystem
DOTFILES_ZSH="$HOME/dotfiles/zsh"
zplug "$DOTFILES_ZSH", from:local, use:"**/*.zsh"
zplug "$DOTFILES_ZSH/fzf-kubectl", from:local, use:"__fzf-kubectl*", as:command

zplug "$HOME", from:local, use:".secret-envs.sh"

zplug load

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export GOROOT="/usr/local/opt/go/libexec"
export PATH="$PATH:$GOPATH/bin"

export PATH="$PATH:/Applications/Xcode.app/Contents/Developer/usr/bin"


export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/elias.jordan/.sdkman"
[[ -s "/Users/elias.jordan/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/elias.jordan/.sdkman/bin/sdkman-init.sh"


